php:
  preset: laravel
  disabled:
    - alpha_ordered_imports
    - single_class_element_per_statement
    - unused_use
  enabled:
    - length_ordered_imports
  finder:
    not-name:
      - index.php
      - server.php
